version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: opportunity_scout_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always